### ISSUE TITLE
Bug located in "solver.solution"

### ISSUE THREAD

**Issue by RebelYoung** [ansys/pyfluent#2683]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

In version `0.19.2`, it is different for the object type returned from `solver.solution`, which is `dict` other than `ansys.fluent.core.solution` in `0.18.x`.
It makes the feature incorrect, for example,
```
solver.solution.report_definitions.drag['drag'] = {}
drag = solver.solution.report_definitions.drag['drag']
drag.force_vector=[1,0,1]
# AttributeError: 'dict' object has no attribute 'report_definitions'
```
or 
```
solver.solution.controls
# AttributeError: 'dict' object has no attribute 'controls'
```
I can't change any solution setting with dictory for other case.

### 📝 Steps to reproduce

```
# in 0.18.x
solution = solver.solution()  # it is a dict
solver.read('another.cas') # another new cas file
setattr(solver,'solution',solution) # it work for copy all solution for a new cas file! Nice job !!!
# but it doesn't work in 0.19.2

solver.solution.report_definitions.drag['drag'] = {}
drag = solver.solution.report_definitions.drag['drag']
drag.force_vector=[1,0,1]
# good job ,but it also failed in 0.19.2.
```

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

`2024R1`

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
(Rebel_py39) D:\Rebel\2024\03\pyf>python -m pip freeze
ansys-api-fluent==0.3.22
ansys-api-platform-instancemanagement==1.0.0
ansys-fluent-core==0.19.2
ansys-fluent-visualization==0.8.0
ansys-platform-instancemanagement==1.1.2
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1698341106958/work
beartype==0.17.2
certifi==2024.2.2
charset-normalizer==3.3.2
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1710320294760/work
contourpy==1.2.0
cycler==0.12.1
debugpy @ file:///D:/bld/debugpy_1707444604970/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
docker==7.0.0
exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1704921103267/work
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1698579936712/work
fonttools==4.50.0
grpcio==1.62.1
grpcio-health-checking==1.48.2
icecream==2.1.3
idna==3.6
importlib_metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1710971335535/work
importlib_resources==6.4.0
ipykernel @ file:///D:/bld/ipykernel_1708996677248/work
ipython @ file:///D:/bld/ipython_1701831845989/work
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1696326070614/work
jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1710255804825/work
jupyter_core @ file:///D:/bld/jupyter_core_1710257377578/work
kiwisolver==1.4.5
lxml==5.1.0
matplotlib==3.8.3
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
nest_asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1705850609492/work
numpy==1.26.4
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1710075952259/work
pandas==2.2.1
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
pillow==10.2.0
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1706713388748/work
pointwise-glyph-client==2.0.11
pooch==1.8.1
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1702399386289/work
protobuf==3.20.3
psutil @ file:///D:/bld/psutil_1705722541723/work
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1700607939962/work
pyparsing==3.1.2
PySide6==6.6.2
PySide6_Addons==6.6.2
PySide6_Essentials==6.6.2
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1709299778482/work
pytz==2024.1
pyvista==0.43.4
pyvistaqt==0.11.0
pywin32==306
PyYAML==6.0.1
pyzmq @ file:///D:/bld/pyzmq_1701783320990/work
QtPy==2.4.1
requests==2.31.0
scipy==1.12.0
scooby==0.9.2
shiboken6==6.6.2
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
tornado @ file:///D:/bld/tornado_1708363257374/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1710254411456/work
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1708904622550/work
tzdata==2024.1
urllib3==2.2.1
vtk==9.3.20230807rc0
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1704731205417/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1695255097490/work
```

**Comment by RebelYoung** [comment]
It means all the features including `solver.solution` failed, in my class, which coding from `pyfluent`.
@mainakk @seanpearsonuk @prmukherj 
```
    def initialize(self, bc_far_name='far', model: str = 'standard'):
        self.total_iterations = 0
        if model == 'hybrid':
            self.solver.solution.initialization.hybrid_initialize() # error
        else:
            self.solver.tui.solve.initialize.compute_defaults.pressure_far_field(
                bc_far_name)
            self.solver.solution.initialization.standard_initialize() #error
```

```
    def add_check_convergence(self, name, report_defs_name, stop_criterion=1.0e-5, initial_values_to_ignore=0):
        self.solver.solution.monitor.convergence_conditions.convergence_reports[name] = {}
        self.solver.solution.monitor.convergence_conditions.convergence_reports[name] = {
            'previous_values_to_consider': 1,
            'initial_values_to_ignore': initial_values_to_ignore,
            'stop_criterion': stop_criterion,
            'report_defs': report_defs_name,
            'print': True, 'plot': False, 'cov': False,
            'active': True, 'x_label': 'iteration'}
```

**Comment by seanpearsonuk** [comment]
@prmukherj @hpohekar Can one of you please try to triage this (for 0.20.0 in the first instance).

**Comment by prmukherj** [comment]
If we want to over-write an object we have to overwrite it with an object only and not it's state.
>>> solution = solver.solution()  # it is setting the 'solution' variable with state of the solution object
>>> solution = solver.solution  # it is setting the 'solution' variable with the copy (by reference) of the solution object.

You should use the second option for your usage as call to any settings object will return it's state. 
Thank you.

cc. @hpohekar, @seanpearsonuk

**Comment by RebelYoung** [comment]
> @prmukherj @hpohekar Can one of you please try to triage this (for 0.20.0 in the first instance).



> If we want to over-write an object we have to overwrite it with an object only and not it's state.
> 
> > > > solution = solver.solution()  # it is setting the 'solution' variable with state of the solution object
> > > > solution = solver.solution  # it is setting the 'solution' variable with the copy (by reference) of the solution object.
> 
> You should use the second option for your usage as call to any settings object will return it's state.
> 
> Please let us know if we are missing something here.
> 
> Thank you.
> 
> cc. @hpohekar, @seanpearsonuk

I know "`solution = solver.solution # it is setting the 'solution' variable with the copy (by reference) of the solution object.`".
My meaning is I always use 
```
solution_dict = solver.solution()  # it is a dict
solver.read('another.cas') # another new cas file
setattr(solver,'solution',solution_dict) 
```
it is very effient for a same topo mesh.

**Comment by prmukherj** [comment]
Could you please try:
>>>solution_dict = solver.solution()  # it is a dict
>>>solver.read('another.cas') # another new cas file
>>>solver.solution.set_state(solution_dict)

**Comment by RebelYoung** [comment]
@seanpearsonuk @prmukherj @hpohekar hello,  it is very strange in my work station.
the `solver.solution` returned a object, type `dict` from yesterday to the morning. 
But I restart the fluent just now. it changed into `ansys.fluent.core.solver.settings_241.solution.solution` now , and my function works again.
It keeped for about 5 minites. It change into `dict` type again and function failed.

<img width="714" alt="0530a67e356517c42881652c581354a" src="https://github.com/ansys/pyfluent/assets/59256512/631a4627-0aea-43ea-ba2f-e312e675445e">
<img width="377" alt="4d64e1f28969bd4027f117f90af6cb9" src="https://github.com/ansys/pyfluent/assets/59256512/cb69324c-95d0-45fc-b453-1bc67c020d43">

<img width="633" alt="b2444e51dae7e1078718506958d017b" src="https://github.com/ansys/pyfluent/assets/59256512/d7b7bf6e-2549-46b2-9f21-682b7f09f9c0">

**Comment by RebelYoung** [comment]
> Could you please try:
> 
> > > > solution_dict = solver.solution()  # it is a dict
> > > > solver.read('another.cas') # another new cas file
> > > > solver.solution.set_state(solution_dict)
> 
> This might help you achieve what you want. Thank you

![image](https://github.com/ansys/pyfluent/assets/59256512/736d1d9c-a1af-4924-850f-a5c988cecb42)

the `solver.solution` type differs in my work station so it failed.

**Comment by seanpearsonuk** [comment]
@RebelYoung is there a full script that you can provide, which we can use to reproduce a bug reliably?
